<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4iM25zo\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4iM25zo/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container4iM25zo.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container4iM25zo\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container4iM25zo\App_KernelDevDebugContainer([
    'container.build_hash' => '4iM25zo',
    'container.build_id' => 'b2c176f9',
    'container.build_time' => 1674062470,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4iM25zo');
